export const ADD_RESULT = "ADD_RESULT";
export const CHOICE_LOADING = "CHOICE_LOADING";
export const CHOICE_FAILED = "CHOICE_FAILED";
export const ADD_SEARCH = "ADD_SEARCH";
export const SEARCH_LOADING = "SEARCH_LOADING";
export const SEARCH_FAILED = "SEARCH_FAILED";